insert into ch_jobactivity(jobact_id, job_id, actid) values(1, 2, 1);
insert into ch_jobactivity(jobact_id, job_id, actid) values(2, 2, 2);
insert into ch_jobactivity(jobact_id, job_id, actid) values(3, 2, 3);
insert into ch_jobactivity(jobact_id, job_id, actid) values(4, 2, 4);
insert into ch_jobactivity(jobact_id, job_id, actid) values(5, 2, 5);
insert into ch_jobactivity(jobact_id, job_id, actid) values(6, 2, 6);
insert into ch_jobactivity(jobact_id, job_id, actid) values(7, 2, 7);
insert into ch_jobactivity(jobact_id, job_id, actid) values(8, 2, 8);
insert into ch_jobactivity(jobact_id, job_id, actid) values(9, 2, 9);