insert into ch_jobactivity(jobact_id, job_code, act_code) values(1, 'PROG', 'NT');
insert into ch_jobactivity(jobact_id, job_code, act_code) values(2, 'PROG', 'WR');
insert into ch_jobactivity(jobact_id, job_code, act_code) values(3, 'PROG', 'DV');
insert into ch_jobactivity(jobact_id, job_code, act_code) values(4, 'PROG', 'DS');
insert into ch_jobactivity(jobact_id, job_code, act_code) values(5, 'PROG', 'VS');
insert into ch_jobactivity(jobact_id, job_code, act_code) values(6, 'PROG', 'HI');
insert into ch_jobactivity(jobact_id, job_code, act_code) values(7, 'PROG', 'MI');
insert into ch_jobactivity(jobact_id, job_code, act_code) values(8, 'PROG', 'GI');
insert into ch_jobactivity(jobact_id, job_code, act_code) values(9, 'PROG', 'CT');