--------------------------------------------------------
--  File created - Thursday-April-14-2016   
--------------------------------------------------------
REM INSERTING into ORA1.CH_ROLE_ACTIVITY
SET DEFINE OFF;
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (1,'HRC','NT','1');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (2,'HRA','WR','1');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (3,'HRS','DV','1');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (4,'HRH','DS','1');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (5,'HRA','VS','1');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (6,'HRM','NT','0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (7,'HRM','WR','0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (8,'HRM','DV','0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (9,'HRM','DS','0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (10,'HRM','VS','0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (11,'HRM','HI','1');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (12,'HIM','NT','0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (13,'HIM','WR','0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (14,'HIM','DV','0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (15,'HIM','DS','0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (16,'HIM','VS','0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (17,'HIM','HI','0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (18,'HIM','MI','1');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (19,'HIM','CT','1');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (20,'HGI','NT','0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (21,'HGI','WR','0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (22,'HGI','DV','0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (23,'HGI','DS','0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (24,'HGI','VS','0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (25,'HGI','HI','0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (26,'HGI','MI','0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (27,'HGI','GI','1');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,ROLECODE,ACTCODE,RAACCESS) values (28,'HGI','CT','1');
