--------------------------------------------------------
--  File created - Thursday-April-14-2016   
--------------------------------------------------------
REM INSERTING into ORA1.CH_ROLE_ACTIVITY
SET DEFINE OFF;
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (1,5,1,'1');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (2,3,2,'1');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (3,2,3,'1');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (4,4,4,'1');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (5,3,5,'1');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (6,1,1,'0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (7,1,2,'0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (8,1,3,'0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (9,1,4,'0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (10,1,5,'0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (11,1,6,'1');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (12,6,1,'0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (13,6,2,'0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (14,6,3,'0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (15,6,4,'0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (16,6,5,'0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (17,6,6,'0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (18,6,7,'1');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (19,6,9,'1');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (20,7,1,'0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (21,7,2,'0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (22,7,3,'0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (23,7,4,'0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (24,7,5,'0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (25,7,6,'0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (26,7,7,'0');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (27,7,8,'1');
Insert into ORA1.CH_ROLE_ACTIVITY (ROLEACTID,HR_ID,ACTID,RAACCESS) values (28,7,9,'1');
